name: Copy Changed Files

on:
  workflow_dispatch:
    inputs:
      since:
        type: string
        description: Since SHA
        required: true
  pull_request:
  push:
    branches:    
      - 'main'

jobs:
  Copy-Changed-Files:
    runs-on: ubuntu-latest
    steps:
      - name: Shallow Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 15

      - name: Preview Changed Files (on Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        run: ./bin/changed-since.sh ${{ github.event.pull_request.base.sha }}

      - name: Configure AWS credentials
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy Changed Files (on main)
        if: ${{ github.event_name == 'push' }}
        run: ./bin/copy-changed-to-s3.sh ${{ github.event.before }}

      - name: Copy Changed Files (on Workflow Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: ./bin/copy-changed-to-s3.sh ${{ github.event.inputs.since }}